version: '3.9'

services:
  api:
    build:
      context: ../AuthApi/AuthApi
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=authdb;Username=postgres;Password=postgres
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    build:
      context: ./authfrontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
volumes:
  pgdata: 
